from setuptools import setup

setup(
    name="org_data_libs",
    version="1.0.96",
    package_dir={"org_data_libs": "src"},
    package_data={"org_data_libs": ["src/sparql_client/queries/get_entity_id_for_instances_of_desired_categories.rq"]},
    description="Library for working with org data Services like Pigment, LDAP, Deel, and other services",
    url="https://stash.int.klarna.net/projects/FIXORGDATA/repos/org-data-libs/browse",
    maintainer="LP Fix Org Data",
    maintainer_email="2ca3cc45f5859b73430aa99d12616dcb@dep.klarna.org",
    license="Klarna Internal",
    install_requires=[
        "klarnaldap>=0.44.0",
        "numpy>=1.26.2",
        "pandas>=2.1.4",
        "requests>=2.31.0",
        "klarna_wiki_api>=0.12.0",
        "pydantic>=2.9.2",
        "pydantic[email]>=2.7.4",
        "wikibase-api==0.1.2",
        "SPARQLWrapper==2.0.0",
        "python-dateutil==2.8.2",
        "aiohttp~=3.9.5",
        "tqdm~=4.66.4",
        "Unidecode~=1.3.8",
        "diskcache~=5.6.3",
        "deel-sdk==1.0.4",
        "tenacity~=9.0.0",
        "pydantic-settings>=2.5.2",
        "Faker~=28.1.0",
        "klarna-authentication>=0.1.0",
        "pycountry==24.6.1",
        "boto3==1.36.9",
        "boto3-stubs==1.36.10",
    ],
    setup_requires=["setuptools_scm"],
    dependency_links=[
        "https://artifactory.klarna.net/artifactory/api/pypi/v-pypi-production/simple",
    ],
    include_package_data=True,
)
